### ISSUE TITLE
missing F.Mask and B.Mask on some connectors

### ISSUE THREAD

**Issue by pointhi** [KiCad/Connectors_Harwin.pretty#6]
connectors like `Harwin_Gecko-G125-MVX` missing `F.Mask` and `B.Mask` for the mounting holes

**Comment by SchrodingersGat** [comment]
@pointhi thanks for the heads up, I will look into this and adjust my script(s)

**Comment by SchrodingersGat** [comment]
See here https://github.com/KiCad/Connectors_Harwin.pretty/pull/7
